import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";


const mergeOne = localFont({
  src: "./fonts/MergeOne-Regular.woff",
  variable: "--font-merge-one",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="relative bg-primary">
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
